export interface Gym {
  id: number
  name: string
  address: string
  city: string
  state: string
  zipCode: string
  distance: string
  rating: number
  reviews: number
  phone: string
  website: string
  email: string
  specialties: string[]
  priceRange: "$" | "$$" | "$$$" | "$$$$"
  hours: {
    monday: string
    tuesday: string
    wednesday: string
    thursday: string
    friday: string
    saturday: string
    sunday: string
  }
  amenities: string[]
  image: string
  featured: boolean
  description: string
  instructors: Array<{
    name: string
    specialty: string
    experience: string
  }>
  classes: Array<{
    name: string
    level: string
    duration: string
    schedule: string[]
    price: number
  }>
  coordinates: {
    lat: number
    lng: number
  }
}

export const gymsDatabase: Gym[] = [
  {
    id: 1,
    name: "Elite Combat Academy",
    address: "123 Fighter St",
    city: "Downtown",
    state: "CA",
    zipCode: "90210",
    distance: "0.8 miles",
    rating: 4.8,
    reviews: 156,
    phone: "(555) 123-4567",
    website: "elitecombat.com",
    email: "info@elitecombat.com",
    specialties: ["MMA", "Boxing", "Muay Thai", "Brazilian Jiu-Jitsu"],
    priceRange: "$$$",
    hours: {
      monday: "6 AM - 10 PM",
      tuesday: "6 AM - 10 PM",
      wednesday: "6 AM - 10 PM",
      thursday: "6 AM - 10 PM",
      friday: "6 AM - 10 PM",
      saturday: "8 AM - 8 PM",
      sunday: "10 AM - 6 PM",
    },
    amenities: ["Showers", "Parking", "Equipment", "Sauna", "Nutrition Bar"],
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
    description: "Premier MMA training facility with world-class instructors and state-of-the-art equipment.",
    instructors: [
      { name: "Marcus Johnson", specialty: "MMA", experience: "15 years" },
      { name: "Sofia Martinez", specialty: "Boxing", experience: "12 years" },
      { name: "Carlos Silva", specialty: "BJJ", experience: "18 years" },
    ],
    classes: [
      {
        name: "Beginner MMA",
        level: "Beginner",
        duration: "60 min",
        schedule: ["Mon 7PM", "Wed 7PM", "Fri 7PM"],
        price: 150,
      },
      { name: "Advanced Boxing", level: "Advanced", duration: "90 min", schedule: ["Tue 6PM", "Thu 6PM"], price: 180 },
      {
        name: "BJJ Fundamentals",
        level: "Beginner",
        duration: "75 min",
        schedule: ["Mon 8PM", "Wed 8PM", "Sat 10AM"],
        price: 160,
      },
    ],
    coordinates: { lat: 34.0522, lng: -118.2437 },
  },
  {
    id: 2,
    name: "Women's Self-Defense Center",
    address: "456 Safety Ave",
    city: "Midtown",
    state: "CA",
    zipCode: "90211",
    distance: "1.2 miles",
    rating: 4.9,
    reviews: 89,
    phone: "(555) 234-5678",
    website: "womensdefense.com",
    email: "contact@womensdefense.com",
    specialties: ["Self-Defense", "Krav Maga", "Women's Classes", "Kickboxing"],
    priceRange: "$$",
    hours: {
      monday: "7 AM - 9 PM",
      tuesday: "7 AM - 9 PM",
      wednesday: "7 AM - 9 PM",
      thursday: "7 AM - 9 PM",
      friday: "7 AM - 9 PM",
      saturday: "9 AM - 6 PM",
      sunday: "10 AM - 5 PM",
    },
    amenities: ["Women-Only Hours", "Childcare", "Parking", "Changing Rooms"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Empowering women through practical self-defense training in a supportive environment.",
    instructors: [
      { name: "Rachel Thompson", specialty: "Krav Maga", experience: "10 years" },
      { name: "Lisa Chen", specialty: "Self-Defense", experience: "8 years" },
    ],
    classes: [
      {
        name: "Women's Self-Defense",
        level: "All Levels",
        duration: "60 min",
        schedule: ["Mon 7PM", "Wed 7PM", "Sat 11AM"],
        price: 120,
      },
      { name: "Krav Maga Basics", level: "Beginner", duration: "75 min", schedule: ["Tue 7PM", "Thu 7PM"], price: 140 },
    ],
    coordinates: { lat: 34.0622, lng: -118.2537 },
  },
  {
    id: 3,
    name: "Youth Martial Arts Academy",
    address: "789 Kids Way",
    city: "Suburbs",
    state: "CA",
    zipCode: "90212",
    distance: "2.1 miles",
    rating: 4.7,
    reviews: 203,
    phone: "(555) 345-6789",
    website: "youthmartialarts.com",
    email: "info@youthmartialarts.com",
    specialties: ["Kids Classes", "Karate", "Taekwondo", "Character Building"],
    priceRange: "$$",
    hours: {
      monday: "4 PM - 8 PM",
      tuesday: "4 PM - 8 PM",
      wednesday: "4 PM - 8 PM",
      thursday: "4 PM - 8 PM",
      friday: "4 PM - 8 PM",
      saturday: "9 AM - 3 PM",
      sunday: "Closed",
    },
    amenities: ["Parent Viewing", "Birthday Parties", "Parking", "After School Program"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Building character and confidence in children through traditional martial arts.",
    instructors: [
      { name: "Master Kim", specialty: "Taekwondo", experience: "20 years" },
      { name: "Sensei Williams", specialty: "Karate", experience: "16 years" },
    ],
    classes: [
      {
        name: "Little Dragons (4-6)",
        level: "Beginner",
        duration: "30 min",
        schedule: ["Mon 5PM", "Wed 5PM", "Sat 10AM"],
        price: 100,
      },
      {
        name: "Youth Karate (7-12)",
        level: "All Levels",
        duration: "45 min",
        schedule: ["Tue 5PM", "Thu 5PM", "Sat 11AM"],
        price: 110,
      },
      {
        name: "Teen Taekwondo (13-17)",
        level: "All Levels",
        duration: "60 min",
        schedule: ["Mon 6PM", "Wed 6PM", "Fri 6PM"],
        price: 130,
      },
    ],
    coordinates: { lat: 34.0722, lng: -118.2637 },
  },
  {
    id: 4,
    name: "Fitness & Fight Club",
    address: "321 Workout Blvd",
    city: "East Side",
    state: "CA",
    zipCode: "90213",
    distance: "3.5 miles",
    rating: 4.5,
    reviews: 124,
    phone: "(555) 456-7890",
    website: "fitnessandfight.com",
    email: "hello@fitnessandfight.com",
    specialties: ["Fitness Boxing", "Cardio Kickboxing", "CrossFit", "HIIT"],
    priceRange: "$",
    hours: {
      monday: "5 AM - 11 PM",
      tuesday: "5 AM - 11 PM",
      wednesday: "5 AM - 11 PM",
      thursday: "5 AM - 11 PM",
      friday: "5 AM - 11 PM",
      saturday: "6 AM - 10 PM",
      sunday: "7 AM - 9 PM",
    },
    amenities: ["24/7 Access", "Personal Training", "Nutrition", "Locker Rooms"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "High-energy fitness classes combining martial arts with strength and conditioning.",
    instructors: [
      { name: "Tony Rodriguez", specialty: "Fitness Boxing", experience: "7 years" },
      { name: "Amanda Foster", specialty: "Kickboxing", experience: "9 years" },
    ],
    classes: [
      {
        name: "Cardio Kickboxing",
        level: "All Levels",
        duration: "45 min",
        schedule: ["Daily 6AM", "Daily 7PM"],
        price: 80,
      },
      { name: "Fitness Boxing", level: "All Levels", duration: "50 min", schedule: ["Mon/Wed/Fri 6PM"], price: 90 },
    ],
    coordinates: { lat: 34.0422, lng: -118.2337 },
  },
  {
    id: 5,
    name: "Iron Temple Gym",
    address: "567 Strength St",
    city: "Industrial District",
    state: "CA",
    zipCode: "90214",
    distance: "4.2 miles",
    rating: 4.6,
    reviews: 178,
    phone: "(555) 567-8901",
    website: "irontemple.com",
    email: "train@irontemple.com",
    specialties: ["Powerlifting", "Strongman", "Boxing", "Old School Training"],
    priceRange: "$$",
    hours: {
      monday: "5 AM - 10 PM",
      tuesday: "5 AM - 10 PM",
      wednesday: "5 AM - 10 PM",
      thursday: "5 AM - 10 PM",
      friday: "5 AM - 10 PM",
      saturday: "7 AM - 8 PM",
      sunday: "8 AM - 6 PM",
    },
    amenities: ["Heavy Bags", "Olympic Lifting", "Chalk", "Hardcore Atmosphere"],
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
    description: "Old-school training facility for serious athletes and fighters.",
    instructors: [
      { name: "Big Mike Thompson", specialty: "Boxing", experience: "25 years" },
      { name: "Iron Joe Martinez", specialty: "Strength Training", experience: "20 years" },
    ],
    classes: [
      { name: "Heavy Bag Boxing", level: "All Levels", duration: "60 min", schedule: ["Tue/Thu 7PM"], price: 100 },
      {
        name: "Fighter Conditioning",
        level: "Advanced",
        duration: "90 min",
        schedule: ["Mon/Wed/Fri 6AM"],
        price: 120,
      },
    ],
    coordinates: { lat: 34.0322, lng: -118.2237 },
  },
  {
    id: 6,
    name: "Zen Martial Arts Studio",
    address: "890 Peaceful Way",
    city: "Westside",
    state: "CA",
    zipCode: "90215",
    distance: "2.8 miles",
    rating: 4.8,
    reviews: 95,
    phone: "(555) 678-9012",
    website: "zenmartialarts.com",
    email: "info@zenmartialarts.com",
    specialties: ["Aikido", "Tai Chi", "Meditation", "Traditional Karate"],
    priceRange: "$$",
    hours: {
      monday: "6 AM - 9 PM",
      tuesday: "6 AM - 9 PM",
      wednesday: "6 AM - 9 PM",
      thursday: "6 AM - 9 PM",
      friday: "6 AM - 9 PM",
      saturday: "8 AM - 6 PM",
      sunday: "9 AM - 5 PM",
    },
    amenities: ["Meditation Room", "Traditional Dojo", "Tea Ceremony", "Garden"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Traditional martial arts training focused on mind, body, and spirit development.",
    instructors: [
      { name: "Sensei Yamamoto", specialty: "Aikido", experience: "30 years" },
      { name: "Master Liu", specialty: "Tai Chi", experience: "25 years" },
    ],
    classes: [
      { name: "Aikido Fundamentals", level: "Beginner", duration: "75 min", schedule: ["Mon/Wed 7PM"], price: 140 },
      { name: "Tai Chi", level: "All Levels", duration: "60 min", schedule: ["Tue/Thu 8AM", "Sat 9AM"], price: 100 },
    ],
    coordinates: { lat: 34.0522, lng: -118.2737 },
  },
  {
    id: 7,
    name: "Submission Academy",
    address: "234 Grappling Rd",
    city: "South Bay",
    state: "CA",
    zipCode: "90216",
    distance: "5.1 miles",
    rating: 4.7,
    reviews: 142,
    phone: "(555) 789-0123",
    website: "submissionacademy.com",
    email: "roll@submissionacademy.com",
    specialties: ["Brazilian Jiu-Jitsu", "Wrestling", "Submission Grappling", "No-Gi"],
    priceRange: "$$$",
    hours: {
      monday: "6 AM - 10 PM",
      tuesday: "6 AM - 10 PM",
      wednesday: "6 AM - 10 PM",
      thursday: "6 AM - 10 PM",
      friday: "6 AM - 10 PM",
      saturday: "9 AM - 6 PM",
      sunday: "10 AM - 4 PM",
    },
    amenities: ["Competition Team", "Open Mat", "Showers", "Pro Shop"],
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
    description: "Elite Brazilian Jiu-Jitsu and grappling academy with world-class instruction.",
    instructors: [
      { name: "Professor Santos", specialty: "BJJ", experience: "22 years" },
      { name: "Coach Anderson", specialty: "Wrestling", experience: "15 years" },
    ],
    classes: [
      { name: "BJJ Fundamentals", level: "Beginner", duration: "75 min", schedule: ["Mon/Wed/Fri 7PM"], price: 180 },
      { name: "Advanced BJJ", level: "Advanced", duration: "90 min", schedule: ["Tue/Thu 8PM"], price: 200 },
      { name: "Wrestling", level: "All Levels", duration: "60 min", schedule: ["Sat 11AM"], price: 150 },
    ],
    coordinates: { lat: 34.0122, lng: -118.2137 },
  },
  {
    id: 8,
    name: "Muay Thai Warriors",
    address: "456 Kickboxing Ave",
    city: "Thai Town",
    state: "CA",
    zipCode: "90217",
    distance: "3.7 miles",
    rating: 4.9,
    reviews: 167,
    phone: "(555) 890-1234",
    website: "muaythaiwarriors.com",
    email: "train@muaythaiwarriors.com",
    specialties: ["Muay Thai", "Kickboxing", "Thai Boxing", "Conditioning"],
    priceRange: "$$",
    hours: {
      monday: "6 AM - 9 PM",
      tuesday: "6 AM - 9 PM",
      wednesday: "6 AM - 9 PM",
      thursday: "6 AM - 9 PM",
      friday: "6 AM - 9 PM",
      saturday: "8 AM - 6 PM",
      sunday: "9 AM - 5 PM",
    },
    amenities: ["Thai Pads", "Heavy Bags", "Ring", "Traditional Training"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Authentic Muay Thai training with traditional techniques and conditioning.",
    instructors: [
      { name: "Kru Somchai", specialty: "Muay Thai", experience: "28 years" },
      { name: "Ajarn Niran", specialty: "Traditional Thai Boxing", experience: "35 years" },
    ],
    classes: [
      { name: "Muay Thai Basics", level: "Beginner", duration: "60 min", schedule: ["Mon/Wed/Fri 7PM"], price: 130 },
      { name: "Advanced Muay Thai", level: "Advanced", duration: "90 min", schedule: ["Tue/Thu 8PM"], price: 160 },
      { name: "Thai Conditioning", level: "All Levels", duration: "45 min", schedule: ["Sat 10AM"], price: 100 },
    ],
    coordinates: { lat: 34.0622, lng: -118.2437 },
  },
  {
    id: 9,
    name: "Combat Sports Center",
    address: "789 Fighter Blvd",
    city: "Arena District",
    state: "CA",
    zipCode: "90218",
    distance: "1.9 miles",
    rating: 4.4,
    reviews: 198,
    phone: "(555) 901-2345",
    website: "combatsportscenter.com",
    email: "fight@combatsportscenter.com",
    specialties: ["MMA", "Boxing", "Kickboxing", "Wrestling", "BJJ"],
    priceRange: "$$$",
    hours: {
      monday: "5 AM - 11 PM",
      tuesday: "5 AM - 11 PM",
      wednesday: "5 AM - 11 PM",
      thursday: "5 AM - 11 PM",
      friday: "5 AM - 11 PM",
      saturday: "7 AM - 9 PM",
      sunday: "8 AM - 8 PM",
    },
    amenities: ["Octagon", "Boxing Ring", "Full Gym", "Recovery Center"],
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
    description: "Complete combat sports facility with professional-grade equipment and training.",
    instructors: [
      { name: "Coach Rivera", specialty: "MMA", experience: "18 years" },
      { name: "Trainer Johnson", specialty: "Boxing", experience: "14 years" },
      { name: "Professor Kim", specialty: "BJJ", experience: "16 years" },
    ],
    classes: [
      { name: "MMA Fundamentals", level: "Beginner", duration: "75 min", schedule: ["Mon/Wed/Fri 6PM"], price: 170 },
      { name: "Pro Boxing", level: "Advanced", duration: "90 min", schedule: ["Tue/Thu 7PM"], price: 190 },
      { name: "Open Training", level: "All Levels", duration: "120 min", schedule: ["Sat 2PM"], price: 50 },
    ],
    coordinates: { lat: 34.0422, lng: -118.2537 },
  },
  {
    id: 10,
    name: "Legends Boxing Gym",
    address: "123 Champion St",
    city: "Historic District",
    state: "CA",
    zipCode: "90219",
    distance: "4.8 miles",
    rating: 4.6,
    reviews: 134,
    phone: "(555) 012-3456",
    website: "legendsboxing.com",
    email: "legends@legendsboxing.com",
    specialties: ["Boxing", "Amateur Boxing", "Professional Training", "Youth Boxing"],
    priceRange: "$$",
    hours: {
      monday: "6 AM - 9 PM",
      tuesday: "6 AM - 9 PM",
      wednesday: "6 AM - 9 PM",
      thursday: "6 AM - 9 PM",
      friday: "6 AM - 9 PM",
      saturday: "8 AM - 6 PM",
      sunday: "10 AM - 4 PM",
    },
    amenities: ["Boxing Ring", "Speed Bags", "Heavy Bags", "Hall of Fame"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Historic boxing gym that has trained champions for over 50 years.",
    instructors: [
      { name: "Coach Martinez", specialty: "Boxing", experience: "32 years" },
      { name: "Trainer Wilson", specialty: "Amateur Boxing", experience: "19 years" },
    ],
    classes: [
      { name: "Boxing Fundamentals", level: "Beginner", duration: "60 min", schedule: ["Mon/Wed/Fri 6PM"], price: 120 },
      { name: "Competitive Boxing", level: "Advanced", duration: "90 min", schedule: ["Tue/Thu 7PM"], price: 150 },
      { name: "Youth Boxing", level: "Youth", duration: "45 min", schedule: ["Sat 10AM"], price: 80 },
    ],
    coordinates: { lat: 34.0222, lng: -118.2337 },
  },
  {
    id: 11,
    name: "Phoenix Fitness & Martial Arts",
    address: "567 Rising Ave",
    city: "New Town",
    state: "CA",
    zipCode: "90220",
    distance: "6.2 miles",
    rating: 4.3,
    reviews: 87,
    phone: "(555) 123-4567",
    website: "phoenixfitness.com",
    email: "rise@phoenixfitness.com",
    specialties: ["Fitness", "Martial Arts", "Personal Training", "Group Classes"],
    priceRange: "$",
    hours: {
      monday: "5 AM - 10 PM",
      tuesday: "5 AM - 10 PM",
      wednesday: "5 AM - 10 PM",
      thursday: "5 AM - 10 PM",
      friday: "5 AM - 10 PM",
      saturday: "7 AM - 8 PM",
      sunday: "8 AM - 7 PM",
    },
    amenities: ["Full Gym", "Group Classes", "Personal Training", "Nutrition Coaching"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Modern fitness facility combining traditional martial arts with contemporary training methods.",
    instructors: [
      { name: "Sarah Johnson", specialty: "Fitness", experience: "8 years" },
      { name: "Mike Chen", specialty: "Martial Arts", experience: "12 years" },
    ],
    classes: [
      {
        name: "Martial Arts Fitness",
        level: "All Levels",
        duration: "45 min",
        schedule: ["Daily 6AM", "Daily 6PM"],
        price: 70,
      },
      { name: "Self-Defense", level: "Beginner", duration: "60 min", schedule: ["Sat 11AM"], price: 90 },
    ],
    coordinates: { lat: 34.0822, lng: -118.2637 },
  },
  {
    id: 12,
    name: "Warrior's Path Dojo",
    address: "890 Discipline Way",
    city: "Mountain View",
    state: "CA",
    zipCode: "90221",
    distance: "7.1 miles",
    rating: 4.7,
    reviews: 112,
    phone: "(555) 234-5678",
    website: "warriorspath.com",
    email: "path@warriorspath.com",
    specialties: ["Karate", "Judo", "Kendo", "Traditional Arts"],
    priceRange: "$$",
    hours: {
      monday: "6 AM - 9 PM",
      tuesday: "6 AM - 9 PM",
      wednesday: "6 AM - 9 PM",
      thursday: "6 AM - 9 PM",
      friday: "6 AM - 9 PM",
      saturday: "8 AM - 6 PM",
      sunday: "9 AM - 5 PM",
    },
    amenities: ["Traditional Dojo", "Weapons Training", "Meditation", "Cultural Classes"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Traditional Japanese martial arts dojo emphasizing discipline, respect, and technique.",
    instructors: [
      { name: "Sensei Takeshi", specialty: "Karate", experience: "26 years" },
      { name: "Sensei Akiko", specialty: "Judo", experience: "21 years" },
    ],
    classes: [
      { name: "Shotokan Karate", level: "All Levels", duration: "75 min", schedule: ["Mon/Wed/Fri 7PM"], price: 140 },
      { name: "Judo", level: "All Levels", duration: "90 min", schedule: ["Tue/Thu 7PM"], price: 150 },
      { name: "Kendo", level: "Intermediate", duration: "60 min", schedule: ["Sat 2PM"], price: 120 },
    ],
    coordinates: { lat: 34.0922, lng: -118.2737 },
  },
  {
    id: 13,
    name: "Street Smart Self-Defense",
    address: "345 Reality St",
    city: "Urban Center",
    state: "CA",
    zipCode: "90222",
    distance: "2.3 miles",
    rating: 4.5,
    reviews: 76,
    phone: "(555) 345-6789",
    website: "streetsmartdefense.com",
    email: "defend@streetsmartdefense.com",
    specialties: ["Krav Maga", "Self-Defense", "Reality-Based Training", "Situational Awareness"],
    priceRange: "$$",
    hours: {
      monday: "6 AM - 9 PM",
      tuesday: "6 AM - 9 PM",
      wednesday: "6 AM - 9 PM",
      thursday: "6 AM - 9 PM",
      friday: "6 AM - 9 PM",
      saturday: "9 AM - 5 PM",
      sunday: "10 AM - 4 PM",
    },
    amenities: ["Scenario Training", "Weapons Defense", "Stress Testing", "Parking"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Reality-based self-defense training for real-world situations and threats.",
    instructors: [
      { name: "Instructor Davis", specialty: "Krav Maga", experience: "14 years" },
      { name: "Coach Thompson", specialty: "Reality Training", experience: "11 years" },
    ],
    classes: [
      { name: "Krav Maga Basics", level: "Beginner", duration: "60 min", schedule: ["Mon/Wed 7PM"], price: 130 },
      { name: "Advanced Self-Defense", level: "Advanced", duration: "75 min", schedule: ["Tue/Thu 8PM"], price: 150 },
      { name: "Women's Self-Defense", level: "All Levels", duration: "90 min", schedule: ["Sat 10AM"], price: 100 },
    ],
    coordinates: { lat: 34.0522, lng: -118.2337 },
  },
  {
    id: 14,
    name: "Olympic Training Center",
    address: "678 Excellence Blvd",
    city: "Sports Complex",
    state: "CA",
    zipCode: "90223",
    distance: "8.5 miles",
    rating: 4.8,
    reviews: 203,
    phone: "(555) 456-7890",
    website: "olympictraining.com",
    email: "elite@olympictraining.com",
    specialties: ["Olympic Wrestling", "Judo", "Boxing", "Elite Training"],
    priceRange: "$$$$",
    hours: {
      monday: "5 AM - 10 PM",
      tuesday: "5 AM - 10 PM",
      wednesday: "5 AM - 10 PM",
      thursday: "5 AM - 10 PM",
      friday: "5 AM - 10 PM",
      saturday: "6 AM - 8 PM",
      sunday: "7 AM - 7 PM",
    },
    amenities: ["Olympic Facilities", "Sports Science", "Recovery Center", "Nutrition"],
    image: "/placeholder.svg?height=200&width=300",
    featured: true,
    description: "Elite training facility for Olympic-level athletes and serious competitors.",
    instructors: [
      { name: "Coach Rodriguez", specialty: "Wrestling", experience: "Olympic Coach" },
      { name: "Master Kim", specialty: "Judo", experience: "Olympic Medalist" },
    ],
    classes: [
      { name: "Elite Wrestling", level: "Advanced", duration: "120 min", schedule: ["Mon/Wed/Fri 6AM"], price: 300 },
      { name: "Olympic Judo", level: "Advanced", duration: "90 min", schedule: ["Tue/Thu 7AM"], price: 250 },
      { name: "Competition Prep", level: "Elite", duration: "180 min", schedule: ["Sat 9AM"], price: 400 },
    ],
    coordinates: { lat: 34.1022, lng: -118.2837 },
  },
  {
    id: 15,
    name: "Family Martial Arts Center",
    address: "901 Family Way",
    city: "Suburban Heights",
    state: "CA",
    zipCode: "90224",
    distance: "5.7 miles",
    rating: 4.4,
    reviews: 156,
    phone: "(555) 567-8901",
    website: "familymartialarts.com",
    email: "family@familymartialarts.com",
    specialties: ["Family Classes", "Karate", "Taekwondo", "Character Development"],
    priceRange: "$$",
    hours: {
      monday: "4 PM - 9 PM",
      tuesday: "4 PM - 9 PM",
      wednesday: "4 PM - 9 PM",
      thursday: "4 PM - 9 PM",
      friday: "4 PM - 9 PM",
      saturday: "9 AM - 5 PM",
      sunday: "10 AM - 4 PM",
    },
    amenities: ["Family Discounts", "Birthday Parties", "Summer Camps", "Parent Classes"],
    image: "/placeholder.svg?height=200&width=300",
    featured: false,
    description: "Family-friendly martial arts center where parents and children can train together.",
    instructors: [
      { name: "Master Johnson", specialty: "Family Programs", experience: "18 years" },
      { name: "Instructor Lee", specialty: "Youth Development", experience: "12 years" },
    ],
    classes: [
      { name: "Family Karate", level: "All Levels", duration: "60 min", schedule: ["Sat 11AM", "Sun 2PM"], price: 120 },
      { name: "Parent & Child", level: "Beginner", duration: "45 min", schedule: ["Sat 10AM"], price: 100 },
      { name: "Teen Leadership", level: "Intermediate", duration: "75 min", schedule: ["Mon/Wed 6PM"], price: 140 },
    ],
    coordinates: { lat: 34.0722, lng: -118.2937 },
  },
]
