export interface Product {
  id: number
  name: string
  category: string
  price: number
  originalPrice?: number
  rating: number
  reviews: number
  image: string
  level: "Beginner" | "Intermediate" | "Professional" | "All Levels"
  brand: string
  features: string[]
  inStock: boolean
  bestseller: boolean
  description: string
  specifications: {
    material?: string
    weight?: string
    size?: string
    color?: string[]
    warranty?: string
  }
  tags: string[]
}

export const productsDatabase: Product[] = [
  {
    id: 1,
    name: "Elite Pro Boxing Gloves",
    category: "Gloves",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.8,
    reviews: 234,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "FightGear Pro",
    features: ["Genuine Leather", "Gel Padding", "Velcro Closure", "Moisture Wicking"],
    inStock: true,
    bestseller: true,
    description: "Premium boxing gloves designed for professional fighters and serious training.",
    specifications: {
      material: "Genuine Leather",
      weight: "16 oz",
      size: "S, M, L, XL",
      color: ["Black", "Red", "Blue"],
      warranty: "1 Year",
    },
    tags: ["boxing", "professional", "leather", "training"],
  },
  {
    id: 2,
    name: "Beginner Training Gloves",
    category: "Gloves",
    price: 49.99,
    rating: 4.5,
    reviews: 156,
    image: "/placeholder.svg?height=300&width=300",
    level: "Beginner",
    brand: "StartStrong",
    features: ["Synthetic Leather", "Foam Padding", "Hook & Loop", "Breathable"],
    inStock: true,
    bestseller: false,
    description: "Perfect starter gloves for beginners learning boxing fundamentals.",
    specifications: {
      material: "Synthetic Leather",
      weight: "12 oz, 14 oz",
      size: "S, M, L",
      color: ["Black", "White", "Red"],
      warranty: "6 Months",
    },
    tags: ["boxing", "beginner", "affordable", "training"],
  },
  {
    id: 3,
    name: "Heavy Bag - 100lb",
    category: "Bags",
    price: 199.99,
    rating: 4.7,
    reviews: 89,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "IronCore",
    features: ["Synthetic Leather", "Pre-filled", "Heavy Duty Chain", "Reinforced Seams"],
    inStock: true,
    bestseller: false,
    description: "Professional-grade heavy bag for serious training and conditioning.",
    specifications: {
      material: "Synthetic Leather",
      weight: "100 lbs",
      size: '48" x 14"',
      color: ["Black"],
      warranty: "2 Years",
    },
    tags: ["heavy bag", "training", "conditioning", "professional"],
  },
  {
    id: 4,
    name: "Speed Bag Platform Set",
    category: "Bags",
    price: 89.99,
    rating: 4.3,
    reviews: 67,
    image: "/placeholder.svg?height=300&width=300",
    level: "Beginner",
    brand: "QuickHit",
    features: ["Adjustable Height", "Swivel Mount", "Includes Bag", "Easy Assembly"],
    inStock: false,
    bestseller: false,
    description: "Complete speed bag setup for developing hand-eye coordination and timing.",
    specifications: {
      material: "Steel Frame",
      weight: "25 lbs",
      size: "Adjustable 8-12 feet",
      color: ["Black", "Silver"],
      warranty: "1 Year",
    },
    tags: ["speed bag", "coordination", "timing", "complete set"],
  },
  {
    id: 5,
    name: "MMA Training Shorts",
    category: "Uniforms",
    price: 59.99,
    rating: 4.6,
    reviews: 123,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "FightWear",
    features: ["Moisture Wicking", "Flexible Waistband", "Reinforced Seams", "Quick Dry"],
    inStock: true,
    bestseller: true,
    description: "High-performance MMA shorts designed for intense training and competition.",
    specifications: {
      material: "Polyester Blend",
      weight: "0.5 lbs",
      size: "S, M, L, XL, XXL",
      color: ["Black", "Blue", "Red", "White"],
      warranty: "6 Months",
    },
    tags: ["mma", "shorts", "training", "competition"],
  },
  {
    id: 6,
    name: "Headgear Protection",
    category: "Protection",
    price: 79.99,
    rating: 4.4,
    reviews: 91,
    image: "/placeholder.svg?height=300&width=300",
    level: "Beginner",
    brand: "SafeGuard",
    features: ["Foam Padding", "Adjustable Straps", "Chin Protection", "Lightweight"],
    inStock: true,
    bestseller: false,
    description: "Essential head protection for sparring and training sessions.",
    specifications: {
      material: "Synthetic Leather",
      weight: "1.2 lbs",
      size: "S, M, L",
      color: ["Black", "Red", "Blue"],
      warranty: "1 Year",
    },
    tags: ["headgear", "protection", "sparring", "safety"],
  },
  {
    id: 7,
    name: "Professional Shin Guards",
    category: "Protection",
    price: 94.99,
    rating: 4.7,
    reviews: 145,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "TitanGuard",
    features: ["Gel Padding", "Instep Protection", "Velcro Straps", "Lightweight Design"],
    inStock: true,
    bestseller: true,
    description: "Premium shin guards offering maximum protection for Muay Thai and kickboxing.",
    specifications: {
      material: "Genuine Leather",
      weight: "2.1 lbs",
      size: "S, M, L, XL",
      color: ["Black", "White", "Red"],
      warranty: "2 Years",
    },
    tags: ["shin guards", "muay thai", "kickboxing", "protection"],
  },
  {
    id: 8,
    name: "Double End Bag",
    category: "Bags",
    price: 69.99,
    rating: 4.5,
    reviews: 78,
    image: "/placeholder.svg?height=300&width=300",
    level: "Intermediate",
    brand: "FlexTrain",
    features: ["Elastic Cords", "Adjustable Tension", "Durable Construction", "Compact Size"],
    inStock: true,
    bestseller: false,
    description: "Improve accuracy and timing with this responsive double end training bag.",
    specifications: {
      material: "Synthetic Leather",
      weight: "8 lbs",
      size: '9" x 6"',
      color: ["Black", "Red"],
      warranty: "1 Year",
    },
    tags: ["double end bag", "accuracy", "timing", "training"],
  },
  {
    id: 9,
    name: "Karate Gi - Traditional",
    category: "Uniforms",
    price: 89.99,
    rating: 4.6,
    reviews: 167,
    image: "/placeholder.svg?height=300&width=300",
    level: "All Levels",
    brand: "TraditionWear",
    features: ["100% Cotton", "Pre-shrunk", "Reinforced Stitching", "Belt Included"],
    inStock: true,
    bestseller: false,
    description: "Traditional karate uniform made from high-quality cotton for comfort and durability.",
    specifications: {
      material: "100% Cotton",
      weight: "1.5 lbs",
      size: "00, 0, 1, 2, 3, 4, 5, 6",
      color: ["White"],
      warranty: "6 Months",
    },
    tags: ["karate", "gi", "traditional", "cotton"],
  },
  {
    id: 10,
    name: "Focus Mitts - Pro Series",
    category: "Training Equipment",
    price: 74.99,
    rating: 4.8,
    reviews: 198,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "ProTarget",
    features: ["Curved Design", "Shock Absorption", "Secure Grip", "Lightweight"],
    inStock: true,
    bestseller: true,
    description: "Professional focus mitts for precision training and combination work.",
    specifications: {
      material: "Genuine Leather",
      weight: "1.8 lbs",
      size: "One Size",
      color: ["Black/Red", "Black/Blue"],
      warranty: "1 Year",
    },
    tags: ["focus mitts", "training", "precision", "professional"],
  },
  {
    id: 11,
    name: "Grappling Dummy - 70lb",
    category: "Training Equipment",
    price: 149.99,
    rating: 4.4,
    reviews: 112,
    image: "/placeholder.svg?height=300&width=300",
    level: "Intermediate",
    brand: "GrapplePro",
    features: ["Unfilled", "Durable Canvas", "Multiple Grip Points", "Realistic Shape"],
    inStock: true,
    bestseller: false,
    description: "Practice submissions and takedowns with this realistic grappling dummy.",
    specifications: {
      material: "Canvas",
      weight: "70 lbs (when filled)",
      size: "6 feet tall",
      color: ["Black"],
      warranty: "1 Year",
    },
    tags: ["grappling", "dummy", "bjj", "wrestling"],
  },
  {
    id: 12,
    name: "Hand Wraps - Cotton",
    category: "Accessories",
    price: 12.99,
    rating: 4.3,
    reviews: 289,
    image: "/placeholder.svg?height=300&width=300",
    level: "All Levels",
    brand: "WrapTech",
    features: ["100% Cotton", "180 inches", "Thumb Loop", "Velcro Closure"],
    inStock: true,
    bestseller: true,
    description: "Essential hand protection for boxing and martial arts training.",
    specifications: {
      material: "100% Cotton",
      weight: "0.3 lbs",
      size: "180 inches",
      color: ["Black", "White", "Red", "Blue"],
      warranty: "3 Months",
    },
    tags: ["hand wraps", "protection", "boxing", "essential"],
  },
  {
    id: 13,
    name: "Mouth Guard - Custom Fit",
    category: "Protection",
    price: 24.99,
    rating: 4.5,
    reviews: 156,
    image: "/placeholder.svg?height=300&width=300",
    level: "All Levels",
    brand: "GuardTech",
    features: ["Boil and Bite", "Custom Fit", "Breathing Channels", "Impact Resistant"],
    inStock: true,
    bestseller: false,
    description: "Moldable mouth guard providing superior protection and comfort.",
    specifications: {
      material: "Medical Grade Silicone",
      weight: "0.1 lbs",
      size: "Youth, Adult",
      color: ["Clear", "Black", "Blue", "Red"],
      warranty: "6 Months",
    },
    tags: ["mouth guard", "protection", "custom fit", "safety"],
  },
  {
    id: 14,
    name: "Thai Pads - Curved",
    category: "Training Equipment",
    price: 119.99,
    rating: 4.7,
    reviews: 134,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "ThaiStrike",
    features: ["Curved Design", "Shock Absorption", "Arm Straps", "Durable Construction"],
    inStock: true,
    bestseller: true,
    description: "Authentic Thai pads for Muay Thai training and conditioning.",
    specifications: {
      material: "Genuine Leather",
      weight: "3.2 lbs",
      size: "Standard",
      color: ["Black/Gold", "Red/Black"],
      warranty: "2 Years",
    },
    tags: ["thai pads", "muay thai", "training", "authentic"],
  },
  {
    id: 15,
    name: "BJJ Gi - Competition",
    category: "Uniforms",
    price: 159.99,
    rating: 4.8,
    reviews: 203,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "CompeteWear",
    features: ["IBJJF Legal", "Pearl Weave", "Reinforced Knees", "Pre-shrunk"],
    inStock: true,
    bestseller: true,
    description: "Competition-grade BJJ gi meeting all tournament regulations.",
    specifications: {
      material: "Pearl Weave Cotton",
      weight: "3.5 lbs",
      size: "A0, A1, A2, A3, A4, A5",
      color: ["White", "Blue", "Black"],
      warranty: "1 Year",
    },
    tags: ["bjj", "gi", "competition", "ibjjf"],
  },
  {
    id: 16,
    name: "Kick Shield - Heavy Duty",
    category: "Training Equipment",
    price: 89.99,
    rating: 4.6,
    reviews: 98,
    image: "/placeholder.svg?height=300&width=300",
    level: "Intermediate",
    brand: "ShieldMax",
    features: ["Thick Padding", "Dual Handles", "Curved Design", "Impact Resistant"],
    inStock: true,
    bestseller: false,
    description: "Heavy-duty kick shield for powerful kick training and conditioning.",
    specifications: {
      material: "Synthetic Leather",
      weight: "4.5 lbs",
      size: '24" x 16"',
      color: ["Black", "Red"],
      warranty: "1 Year",
    },
    tags: ["kick shield", "training", "conditioning", "heavy duty"],
  },
  {
    id: 17,
    name: "Wrestling Shoes - Elite",
    category: "Footwear",
    price: 134.99,
    rating: 4.7,
    reviews: 167,
    image: "/placeholder.svg?height=300&width=300",
    level: "Professional",
    brand: "GrappleGrip",
    features: ["Superior Grip", "Ankle Support", "Lightweight", "Breathable"],
    inStock: true,
    bestseller: true,
    description: "High-performance wrestling shoes for competitive athletes.",
    specifications: {
      material: "Synthetic Upper",
      weight: "1.2 lbs",
      size: "6-15 (US)",
      color: ["Black", "Red", "Blue"],
      warranty: "6 Months",
    },
    tags: ["wrestling", "shoes", "grip", "competition"],
  },
  {
    id: 18,
    name: "Makiwara Board - Traditional",
    category: "Training Equipment",
    price: 199.99,
    rating: 4.5,
    reviews: 67,
    image: "/placeholder.svg?height=300&width=300",
    level: "Intermediate",
    brand: "TraditionCraft",
    features: ["Hardwood Construction", "Rope Padding", "Adjustable Height", "Traditional Design"],
    inStock: true,
    bestseller: false,
    description: "Traditional makiwara board for karate conditioning and technique development.",
    specifications: {
      material: "Hardwood",
      weight: "45 lbs",
      size: "6 feet tall",
      color: ["Natural Wood"],
      warranty: "5 Years",
    },
    tags: ["makiwara", "karate", "conditioning", "traditional"],
  },
  {
    id: 19,
    name: "Groin Guard - Pro",
    category: "Protection",
    price: 39.99,
    rating: 4.4,
    reviews: 145,
    image: "/placeholder.svg?height=300&width=300",
    level: "All Levels",
    brand: "GuardPro",
    features: ["Steel Cup", "Comfortable Fit", "Moisture Wicking", "Secure Straps"],
    inStock: true,
    bestseller: false,
    description: "Essential protection for sparring and competition.",
    specifications: {
      material: "Steel/Foam",
      weight: "0.8 lbs",
      size: "S, M, L, XL",
      color: ["Black"],
      warranty: "1 Year",
    },
    tags: ["groin guard", "protection", "sparring", "essential"],
  },
  {
    id: 20,
    name: "Training Timer - Digital",
    category: "Accessories",
    price: 49.99,
    rating: 4.6,
    reviews: 234,
    image: "/placeholder.svg?height=300&width=300",
    level: "All Levels",
    brand: "TimeMax",
    features: ["Interval Timer", "Loud Buzzer", "Easy Programming", "Battery Powered"],
    inStock: true,
    bestseller: true,
    description: "Professional training timer for rounds, intervals, and workouts.",
    specifications: {
      material: "Plastic/Electronic",
      weight: "1.1 lbs",
      size: '8" x 6"',
      color: ["Black"],
      warranty: "2 Years",
    },
    tags: ["timer", "training", "intervals", "professional"],
  },
]
